version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - database:/var/lib/redis/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWD}
      - REDIS_PORT=${REDIS_PORT}
  nestjs:
    container_name: nestjs
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: sh -c "npm start"
    ports:
      - '${API_PORT}:3000'
    depends_on:
      - 'redis'
    env_file:
      - .env

volumes:
  database: