version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      -  database:/var/lib/redis/data:/root/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWD}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  database:
