import { CardBackMap, CardMap } from "../types/cards"

export const cardBackMap : CardBackMap = {
  normal: require('@/assets/images/cards/back/back_1.png'),
  tcs: require('@/assets/images/cards/back/back_4.png'),
};

export const cardMap : CardMap = {
  club: {
    2: require('@/assets/images/cards/front/club-2.png'),
    3: require('@/assets/images/cards/front/club-3.png'),
    4: require('@/assets/images/cards/front/club-4.png'),
    5: require('@/assets/images/cards/front/club-5.png'),
    6: require('@/assets/images/cards/front/club-6.png'),
    7: require('@/assets/images/cards/front/club-7.png'),
    8: require('@/assets/images/cards/front/club-8.png'),
    9: require('@/assets/images/cards/front/club-9.png'),
    10: require('@/assets/images/cards/front/club-10.png'),
    J: require('@/assets/images/cards/front/club-A.png'),
    Q: require('@/assets/images/cards/front/club-A.png'),
    K: require('@/assets/images/cards/front/club-A.png'),
    A: require('@/assets/images/cards/front/club-A.png'),
  },
  diamond: {
    2: require('@/assets/images/cards/front/diamond-2.png'),
    3: require('@/assets/images/cards/front/diamond-3.png'),
    4: require('@/assets/images/cards/front/diamond-4.png'),
    5: require('@/assets/images/cards/front/diamond-5.png'),
    6: require('@/assets/images/cards/front/diamond-6.png'),
    7: require('@/assets/images/cards/front/diamond-7.png'),
    8: require('@/assets/images/cards/front/diamond-8.png'),
    9: require('@/assets/images/cards/front/diamond-9.png'),
    10: require('@/assets/images/cards/front/diamond-10.png'),
    J: require('@/assets/images/cards/front/diamond-A.png'),
    Q: require('@/assets/images/cards/front/diamond-A.png'),
    K: require('@/assets/images/cards/front/diamond-A.png'),
    A: require('@/assets/images/cards/front/diamond-A.png'),
  },
  heart: {
    2: require('@/assets/images/cards/front/heart-2.png'),
    3: require('@/assets/images/cards/front/heart-3.png'),
    4: require('@/assets/images/cards/front/heart-4.png'),
    5: require('@/assets/images/cards/front/heart-5.png'),
    6: require('@/assets/images/cards/front/heart-6.png'),
    7: require('@/assets/images/cards/front/heart-7.png'),
    8: require('@/assets/images/cards/front/heart-8.png'),
    9: require('@/assets/images/cards/front/heart-9.png'),
    10: require('@/assets/images/cards/front/heart-10.png'),
    J: require('@/assets/images/cards/front/heart-A.png'),
    Q: require('@/assets/images/cards/front/heart-A.png'),
    K: require('@/assets/images/cards/front/heart-A.png'),
    A: require('@/assets/images/cards/front/heart-A.png'),
  },
  spade: {
    2: require('@/assets/images/cards/front/spade-2.png'),
    3: require('@/assets/images/cards/front/spade-3.png'),
    4: require('@/assets/images/cards/front/spade-4.png'),
    5: require('@/assets/images/cards/front/spade-5.png'),
    6: require('@/assets/images/cards/front/spade-6.png'),
    7: require('@/assets/images/cards/front/spade-7.png'),
    8: require('@/assets/images/cards/front/spade-8.png'),
    9: require('@/assets/images/cards/front/spade-9.png'),
    10: require('@/assets/images/cards/front/spade-10.png'),
    J: require('@/assets/images/cards/front/spade-A.png'),
    Q: require('@/assets/images/cards/front/spade-A.png'),
    K: require('@/assets/images/cards/front/spade-A.png'),
    A: require('@/assets/images/cards/front/spade-A.png'),
  },
}
